web_browser:
  browser: 'chrome'
  headless: false
  use_profile_directory: true
  use_proxy: false
  path_to_profile_dir: '/Users/macbook/Library/Application Support/Google/Chrome/parser1'
  proxy_host: '127.0.0.1'
  proxy_port: '8080'
  window_width: 1920
  window_height: 1080

login_data:
  login: 'instalogin'
  password: 'instapasswrd'

comment_text_parts:
    - "Au top,"
    - " ton contenu| continue "
    - "lourd |c'est fort"

count_last_posts_process: 20
sleeping_minutes: 8

actions:
  like_comment:
    hashtags:
      - 'florencebymills'
    nicknames:
      - 'selenagomez'
      - 'zendaya'